---
title: "Using Website Boards"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using Website Boards}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc}
---
 
The [local](pins-starting.html), [GitHub](boards-github.html), [Kaggle](boards-kaggle.html) and [RStudio Connect](boards-rsconnect.html) boards provide support for many popular services; however, there are many cases where you would want to share resources in your own website. For instance, [data.gov](https://www.data.gov/), [data.uis.unesco.org](http://data.uis.unesco.org) and [data.nasa.gov](https://data.nasa.gov/) are all examples of websites that contain datasets; in those cases, it can be preferable to avoid moving resources somewhere else. To support `pins` with websites that want to make their data available as `pins`, you can make use of a `data.txt` file to describe them with ease. You can learn more about `data.txt` files at [datatxt.org](https://datatxt.org).

In a nutshell, a `data.txt` file is just a YAML file that you can read and write from R with ease using the `yaml` package. For instance, the following `data.txt` file can be found under [datatxt.org/data.txt](https://datatxt.org/data.txt) to describe the famous `iris` and `mtcars` datasets:

```yaml
- path: iris/data.csv
  name: iris
  rows: 150
  cols: 5
  description: This famous (Fisher's or Anderson's) iris data set gives the measurements
    in centimeters of the variables sepal length and width and petal length and width,
    respectively, for 50 flowers from each of 3 species of iris. The species are Iris
    setosa, versicolor, and virginica.
  type: table
- path: mtcars/data.csv
  name: mtcars
  rows: 32
  cols: 11
  description: The data was extracted from the 1974 Motor Trend US magazine, and comprises
    fuel consumption and 10 aspects of automobile design and performance for 32 automobiles
    (1973–74 models).
  type: table
```

## Registering

As a website owner, you can choose to create a similar file and place it in your website, you do not need to place it in the root of your domain, it can be any valid URL. Once defined, you can create a read-only board using the `datatxt` board. For this particular example, we will reuse [datatxt.org/data.txt](https://datatxt.org/data.txt), but you can replace that with your own domain name, website path, S3 bucket and so on.

```{r eval=FALSE}
board_register_datatxt(name = "txtexample", url = "https://datatxt.org/data.txt")
```
