---
title: "pins 0.3: Azure, GCloud and S3"
description: |
  A new CRAN release for pins adds support to create boards using
  various cloud providers and new functionality to existing boards.
author:
  - name: "Javier Luraschi"
    url: https://github.com/javierluraschi
    affiliation: RStudio
    affiliation_url: https://www.rstudio.com
date: 11-18-2019
categories:
  - Packages
  - Releases
  - Cloud
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(eval = FALSE)
```

A new version of `pins` is available on CRAN! `pins 0.3` comes with many improvements and the following major feaures:
- Use new **cloud boards** to pin resources in Azure, GCloud and S3 storage.
- Retrieve pin information with `pin_info()` to describe the pin's metadata and additional information from each board.

In addition, there is a new [Use Cases](https://rstudio.github.io/pins/articles/use-cases.html) section in our docs, various improvements (see [NEWS](https://rstudio.github.io/pins/news/index.html)) and two community extensions being developed to support [databases](https://edgararuiz.github.io/connections/#pins) and [nextcloud](https://gitlab.com/gwmngilfen/nextcloudr) as boards.

You can install this new version from CRAN as follows:

```r
install.packages("pins")
```

If you need assistance, please open a [GitHub](https://github.com/rstudio/pins/issues/new) issue or chat with us in [Gitter](https://gitter.im/rstudio/pins).

## Cloud Boards

`pins 0.3` adds support to find, retrieve and store resources in various cloud providers like: Microsoft Azure, Google Cloud Platform and Amazon Web Services. To illustrate how they work, lets first try to find the World Bank indicators dataset in Kaggle

```r
library(pins)

pin_find("indicators", board = "kaggle")
```
```
# A tibble: 6 x 4
  name                                            description                             type  board 
  <chr>                                           <chr>                                   <chr> <chr> 
1 worldbank/world-development-indicators          World Development Indicators            files kaggle
2 theworldbank/world-development-indicators       World Development Indicators            files kaggle
3 cdc/chronic-disease                             Chronic Disease Indicators              files kaggle
4 bigquery/worldbank-wdi                          World Development Indicators (WDI) Data files kaggle
5 rajanand/key-indicators-of-annual-health-survey Health Analytics                        files kaggle
6 loveall/human-happiness-indicators              Human Happiness Indicators              files kaggle
```

We can then easily download the "World Development Indicators", beware this is a 2GB download, good thing `pins 0.3` shows a progress bar for large downloads!

```r
pin_get("worldbank/world-development-indicators")
```
```
[1] "/.../worldbank/world-development-indicators/Country.csv"     
[2] "/.../worldbank/world-development-indicators/CountryNotes.csv"
[3] "/.../worldbank/world-development-indicators/database.sqlite" 
[4] "/.../worldbank/world-development-indicators/Footnotes.csv"   
[5] "/.../worldbank/world-development-indicators/hashes.txt"      
[6] "/.../worldbank/world-development-indicators/Indicators.csv"  
[7] "/.../worldbank/world-development-indicators/Series.csv"      
[8] "/.../worldbank/world-development-indicators/SeriesNotes.csv" 
```

The `Indicators.csv` file is really interesting, so let's load it with `readr`:

```r
indicators <- pin_get("worldbank/world-development-indicators")[6] %>%
  readr::read_csv()
```

While you can do really interesting analysis with dataset, in this post we will learn how to easily share this in S3, Google Cloud or Azure storage. More specifically, we will learn how to publish to an S3 board; to publish to other cloud providers, take a look at the Google Cloud and Azure boards articles.

As usual, the first we need to registere the S3 board. When using RStudio, you can use the "New Connection" action to guide you through this process, or you can specify your key and secret  as follows. Please read the S3 board article to understand more secure options to store your credentials!

```r
board_register_s3(name = "rstudio-datasets",
                  bucket  = "rstudio-datasets",
                  key = "VerySecretKey",
                  secret = "EvenMoreImportantSecret")
```

With the S3 board registered, we can simply pin the indicators dataset with `pin()`:

```r
pin(indicators, name = "worldbank/indicators", board = "rstudio-datasets")
```

That's about it! We can now find and retrieve this dataset from S3 with ease.

To make this even easier for others to consume, we've made this S3 bucket public; which means you can now connect to the `rstudio-datasets` board without even having to configure S3. We also made the `rstudio-datasets` bucket available under a `datasets.rstudio.com` domain, which makes it possible to retrieve this dataset with just one line!

```r
pins::pin_get("worldbank/indicators", "https://datasets.rstudio.com")
```
```
# A tibble: 5,656,458 x 6
   CountryName CountryCode IndicatorName                          IndicatorCode    Year      Value
   <chr>       <chr>       <chr>                                  <chr>           <dbl>      <dbl>
 1 Arab World  ARB         Adolescent fertility rate (births per… SP.ADO.TFRT      1960    1.34e+2
 2 Arab World  ARB         Age dependency ratio (% of working-ag… SP.POP.DPND      1960    8.78e+1
 3 Arab World  ARB         Age dependency ratio, old (% of worki… SP.POP.DPND.OL   1960    6.63e+0
 4 Arab World  ARB         Age dependency ratio, young (% of wor… SP.POP.DPND.YG   1960    8.10e+1
 5 Arab World  ARB         Arms exports (SIPRI trend indicator v… MS.MIL.XPRT.KD   1960    3.00e+6
 6 Arab World  ARB         Arms imports (SIPRI trend indicator v… MS.MIL.MPRT.KD   1960    5.38e+8
 7 Arab World  ARB         Birth rate, crude (per 1,000 people)   SP.DYN.CBRT.IN   1960    4.77e+1
 8 Arab World  ARB         CO2 emissions (kt)                     EN.ATM.CO2E.KT   1960    5.96e+4
 9 Arab World  ARB         CO2 emissions (metric tons per capita) EN.ATM.CO2E.PC   1960    6.44e-1
10 Arab World  ARB         CO2 emissions from gaseous fuel consu… EN.ATM.CO2E.GF…  1960    5.04e+0
# … with 5,656,448 more rows
```

A new feature in `pins 0.3` is that, when using a board that starts with `http`, `pins` will automatically register this board as a [website board]() to save you from having to explicitly call `board_register_datatxt(url = "https://datasets.rstudio.com", name = "rstudio-datsets")`.

It's also worth mentioning that `pins` stores the dataset using an R native format, which requires only 72MB and loads much faster than the original CSV and the original 2GB dataset!

In combination with boards like RStudio Connect, `pins` makes it a great tool for easily sharing datasets in your organization or the world.

## Pin Information

RStudio Connect / Kaggle
